apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv
  namespace: dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
  storageClassName: manual
