apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv
  namespace: dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/data
  storageClassName: manual
