apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: dev
spec:
  interval: 30s
  releaseName: airflow-dev
  chart:
    spec:
      chart: airflow
      version: "1.7.0"
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system
  values:
    defaultAirflowTag: "2.9.3"
    airflowVersion: "2.9.3"
    fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
    env:
      - name: "AIRFLOW__CORE__LOAD_EXAMPLES"
        value: "False"
      - name: "AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE"
        value: "dev"
      - name: "AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_REPOSITORY"
        value: "docker.io/nageshnode/airflow-worker"
      - name: "AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_TAG"
        value: "0.2"
      - name: "AIRFLOW__KUBERNETES__RUN_AS_USER"
        value: "root"
      - name: "AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS_ON_FAILURE"
        value: true
      - name: "AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT"
        value: "/opt/airflow/dags"
      - name: "AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH"
        value: "repo/"
    executor: "KubernetesExecutor"
    images:
      airflow:
        repository: "docker.io/nageshnode/airflow"
        tag: "hive"
    createUserJob:
      useHelmHooks: false
    migrateDatabaseJob:
      useHelmHooks: false

    dags:
      persistence:
        enabled: True
      gitSync:
        enabled: True
        repo: "https://github.com/physarum-dev/example-dags-deployment.git"
        branch: "main"
        wait: 60
        subPath: "dags"
    